---
title: "Capstone Project Proposal"
author: "Fadi"
date: "31 December 2017"
output: 
  html_document:
    theme: journal
---

## What is the problem you want to solve?

I would like to find out correlations, commonalities, and trends in citations, specifically brought by accidents. Looking at different factors in play, I hope to gain insight into forecasting accidents or violations based on location, car type, and time of the year.

The motivation behind this project is to find underlying root causes and conditions for accidents and traffic violation. Once unveiled, I am hoping to make effective recommendations based on empirical findings that would lessen frequency of such traffic mishaps.


## Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?

Interpretations from the data analysis would be useful for police department, insurance companies operating in the county, or even the Department of Motor Vehicles when it comes to promoting safer driving practices.

## What data are you going to use for this? How will you acquire this data?
I have acquired a .csv file from data.gov 

<https://catalog.data.gov/dataset/traffic-violations-56dda>

This is a daily record of all traffic violations in Montgomery County in the State of Maryland. The variables could be categorised in three main subgroups:

Time & Location| Accident Details  |  Driver & Vehicle Details |
--------| -------------------------|---------------------------|
Date of Stop | Description|  Vehicle Type|
Time of Stop | Accident  |  Year  |
Location |  Contributed to Accident | Make  |
Lattitude | Personal Injury | Model |
Longitude | Property Damage | Colour  |
Geolocation | Fatal   | Race  |
Work Zone | Belts  |  Gender  |
.         | Alcohol | Driver City |
.       | Charge | Driver State  |
.     |  Commercial License |   |

Other variables may be easily ommitted as their observations are somewhat inconsequential to the analysis:

Agency, SubAgency, HAZMAT, and few others..

## In brief, outline your approach to solving this problem (knowing that this might change later).

In order to streamline the process, I may have to add another column to the data which would group similar violations into one family. This would facilitate the inferential process.

I will also be converting Yes/No observations to binary outputs, as in most of the observations in the "Accident Details" subgroup.

This data set is massive. So a lot of wrangling will be required. I will be utilising dplyr's data manipulation functions to filter and mutate observations and variables. Some substitution will be required in order to streamline the data further.

I will be cleaning up the data, and sort it out chronologically. Some of the factors are irrelevant, such as:
* non-automobile violations
* extremely rare events like HAZMAT-related accidents
* other outliers that may emerge as the data is cleaned
* Other observations that carry NA values amongst essential variables in the "Driver & Vehicle Details" subgroup 

A few intermediary steps may include segregating the dataset by years and/or quarters to facilitate the analysis.

## What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.

The deliverables published on Github would include code that I used to analyse the data, key findings, visual representations, slides, and final remarks regarding inferences to be made.



